# Generated by Django 4.2.1 on 2023-05-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pings',
            name='host',
            field=models.GenericIPAddressField(default='212.77.98.9'),
        ),
        migrations.AddField(
            model_name='pings',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Unknown', 'Unknown')], default='Unknown', max_length=8),
        ),
        migrations.AlterModelTable(
            name='pings',
            table='pings',
        ),
    ]
