# Generated by Django 4.2.1 on 2023-05-18 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pinger', '0003_pings_turbine_name_pings_windfarm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pings',
            name='last_pinged',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last time the IP was pinged'),
        ),
    ]
